# Generated by Django 3.1.7 on 2021-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210331_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='defult.jpg', null=True, upload_to='images/'),
        ),
    ]
