# Generated by Django 3.1.7 on 2021-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210331_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
