# Generated by Django 3.1.1 on 2021-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20210402_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
